name: CI/CD

on:
    pull_request:
        types:
            - closed
        branches:
            - deployment

jobs:
    bump:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-22.04
        permissions:
            contents: write
        outputs:
            new_tag: ${{ steps.bump_version.outputs.new_tag }}
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.merge_commit_sha }}
                  fetch-depth: '0'
            - name: Bump version and push tag
              id: bump_version
              uses: anothrNick/github-tag-action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  WITH_V: true
                  PRERELEASE: false

    # ci:
    #   needs: bump
    #   runs-on: ubuntu-latest

    #   steps:
    #       - name: Checkout
    #         uses: actions/checkout@v3

    #       - name: install dependencies
    #         run: |
    #           npm install
    #         working-directory: ./

    #       - name: Run tests
    #         run: |
    #           npm run test
    #         working-directory: ./

    cd:
        needs: bump
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Login to docker
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USER_NAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              run: |
                  REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
                  docker build \
                     --build-arg DB_HOST=${{ secrets.DB_HOST }} \
                     --build-arg DB_PASS=${{ secrets.DB_PASS }} \
                     --build-arg DB_PORT=${{ secrets.DB_PORT }} \
                     --build-arg DATABASE=${{ secrets.DATABASE }} \
                     --build-arg INFLUX_URL=${{ secrets.INFLUX_URL }} \
                     --build-arg INFLUXDB_TOKEN=${{ secrets.INFLUXDB_TOKEN }} \
                     --build-arg INFLUX_ORG=${{ secrets.INFLUX_ORG }} \
                     --build-arg INFLUX_BUCKET=${{ secrets.INFLUX_BUCKET }} \
                     --build-arg SECRET=${{ secrets.SECRET }} \
                    -t ${{ secrets.DOCKER_USER_NAME }}/${REPO_NAME}:${{ needs.bump.outputs.new_tag }} .
                  docker push ${{ secrets.DOCKER_USER_NAME }}/${REPO_NAME}:${{ needs.bump.outputs.new_tag }}
